### ISSUE TITLE
Fail when there's no packages to install

### ISSUE THREAD

**Issue by ali6p** [heroku/heroku-buildpack-apt#117]
When Aptfile is empty, there is an error during the build:

`       Reading package lists...`
`-----> Installing *.deb`
`dpkg-deb: error: failed to read archive '/tmp/codon/tmp/cache/apt/cache/archives/*.deb': No such file or directory`
 `!     Push rejected, failed to compile Apt app.`
 `!     Push failed`

For a workaround, add a dummy package to Aptfile like:
`fonts-quicksand`

Tested both Heroku stacks heroku-20 and heroku-22.

**Comment by YevKad** [comment]
Same problem, added `fonts-quicksand` to Aptfile, but it didn't help, still get failed to read archive and Push failed errors

**Comment by dzuelke** [comment]
Can I ask, @ali6p and @YevKad, if your `Aptfile`s are empty because you haven't got any packages to install, then what's the purpose of using this buildpack in the first place?

**Comment by ali6p** [comment]
@dzuelke I use another buildpack that needs apt. 

My buildbacks list below. 4. buildpack to enable DataDog and it needs apt.

```
1. heroku-community/apt
2. heroku/php
3. https://github.com/DataDog/heroku-buildpack-datadog.git
4. https://github.com/SpeedCurve-Metrics/heroku-buildpack-php-ddtrace.git
5. heroku/python
```

**Comment by dzuelke** [comment]
@ali6p, those buildpacks do not need the apt buildpack, it does nothing on an empty `Aptfile`, so there is nothing for the other buildpacks to use... where did you get the info that these buildpacks need the Apt buildpack?
