### ISSUE TITLE
trust

### ISSUE THREAD

**Issue by hoover391git** [heroku/heroku-buildpack-apt#128]
1. https://github.com/heroku/heroku-buildpack-apt/blob/4eb4b35d35d0178e5cef73d6998a26ba2c9bbf17/test/utils#L6 forgiveness [package__](url)https://### 0

**Comment by colincasey** [comment]
Closing this as it doesn't contain any actionable information for an issue. If you think this is a mistake then reopen with details regarding the issue you encountered.
