### ISSUE TITLE
Is there a way to add repositories?

### ISSUE THREAD

**Issue by amandasaffer** [heroku/heroku-buildpack-apt#15]
I have the following dependencies:

```
sudo add-apt-repository ppa:fkrull/deadsnakes -y
sudo add-apt-repository ppa:mc3man/trusty-media -y
sudo add-apt-repository ppa:chris-lea/libsodium -y
```

but I'm not sure I can add a repository with this buildpack. Can someone point me in the right direction?

**Comment by sjensen85** [comment]
Can you point us at the material that caused you to close this @amandasaffer ?
