### ISSUE TITLE
--force-yes is deprecated

### ISSUE THREAD

**Issue by csuhta** [heroku/heroku-buildpack-apt#16]
Getting this warning lately when deploying with this buildpack. Ex:

```
-----> Fetching .debs for libjpeg-progs
       Reading package lists...
       Building dependency tree...
       [… snip …]
       Download complete and in download only mode
W: --force-yes is deprecated, use one of the options starting with --allow instead.
```

**Comment by zunda** [comment]
I've [just tested](https://github.com/zunda/heroku-buildpack-apt/tree/deprecate-force-yes) and found that the `--allow-*` options are not available on `cedar-14` stack. We have to wait for end of life of `cedar-14` before we can replace `--force-yes ` with `--allow-*` options.

**Comment by sobrinho** [comment]
Why are we using `--force-yes`? Can't it be replaced by `--assume-yes`?

Ref: https://forums.solydxk.com/viewtopic.php?t=6148

**Comment by surfaceowl** [comment]
@zunda  --the `cedar-14` stack [will EOL in April 2019](https://devcenter.heroku.com/articles/stack)

.... are the ``--allow-*` options available on the `cedar-16 stack`?
