### ISSUE TITLE
Failed to detect app matching no buildpack

### ISSUE THREAD

**Issue by ynotu** [heroku/heroku-buildpack-apt#17]
When trying to deploy this buildpack on cedar-16 in addition to the heroku/nodejs buildpack, I get an "Failed to detect app matching no buildpack" msg and the push is rejected. Furthermore, how do I add the "Aptfile" to include the list of packages, which I want to be installed?

**Comment by Chocksy** [comment]
I had a similar error on a rails cedar-16 and it seems i did not include the right ul. 
`heroku buildpacks:add --index 1 https://github.com/heroku/heroku-buildpack-apt.git` you need the .git at the end. The readme is wrong.

**Comment by edmorley** [comment]
Hi!

> I get an "Failed to detect app matching no buildpack" msg and the push is rejected. Furthermore, how do I add the "Aptfile" to include the list of packages, which I want to be installed?

You need an `Aptfile` in the root of your repository and to follow the steps here:
https://github.com/heroku/heroku-buildpack-apt#example

> you need the .git at the end. The readme is wrong.

Trying now it works for me without the `.git`.

**Comment by mgan59** [comment]
hey, sorry to re-bubble this one.  But I have the following [buildpack for apt](https://github.com/hickory-training/heroku-buildpack-apt)

```shell
 $ git push hickory-dev branch:master
Enumerating objects: 58206, done.
Counting objects: 100% (58206/58206), done.
Delta compression using up to 12 threads
Compressing objects: 100% (16324/16324), done.
Writing objects: 100% (58206/58206), 63.64 MiB | 3.76 MiB/s, done.
Total 58206 (delta 40148), reused 57464 (delta 39657)
remote: Compressing source files... done.
remote: Building source:
remote:
remote: -----> App not compatible with buildpack: https://github.com/hickory-training/heroku-buildpack-apt
remote:        More info: https://devcenter.heroku.com/articles/buildpacks#detection-failure
remote:
remote:  !     Push failed
remote: Verifying deploy...
remote:
remote: !	Push rejected to hickory-dev.
remote:
To https://git.heroku.com/hickory-dev.git
 ! [remote rejected]     dev -> master (pre-receive hook declined)
```

Not sure why it is rejecting, I have an `Aptfile` in place.

I'm running these other build packs:

```shell
$ heroku buildpacks --remote dev
=== hickory-dev Buildpack URLs
1. https://github.com/hickory-training/heroku-buildpack-apt
2. https://github.com/heroku/heroku-buildpack-nodejs
3. https://github.com/heroku/heroku-buildpack-python
```
