### ISSUE TITLE
Support for HTTPS repositories

### ISSUE THREAD

**Issue by excieve** [heroku/heroku-buildpack-apt#26]
With this buildpack now having support for adding repositories through the `Aptfile`, it's still impossible to use HTTPS-only repos as the build fails on lacking an HTTPS apt transport. Adding `apt-transport-https` to the `Aptfile` doesn't work properly because packages are installed after making the repo cache.

Please consider adding the `apt-transport-https` before adding custom repos or alternatively respect the order in the `Aptfile`.

**Comment by kevinburke** [comment]
Would just like to re-up this following @ice799's writeup of the security problems with downloading APT repos over http: https://blog.packagecloud.io/eng/2018/02/21/attacks-against-secure-apt-repositories/

**Comment by tt** [comment]
Since March 27th, the "apt-transport-https" package has been included by default with our stack images (see [this changelog entry](https://devcenter.heroku.com/changelog-items/1389)).

I believe this resolves the issue but feel free to reopen if not.
