### ISSUE TITLE
Proposal: support comments in Aptfile

### ISSUE THREAD

**Issue by OlivierSohn** [heroku/heroku-buildpack-apt#34]
It would be nice to be able to write:

```shell
# This CI file defines packages to be installed while deploying using Heroku.
# It is used by the buildpack https://github.com/heroku/heroku-buildpack-apt.git
package1
# We need package2 because ...
package2
```

**Comment by edmorley** [comment]
Fixed in #24 :-)

This will be available straight away for anyone using the GitHub URL in their buildpacks list, and within a few days if using the `heroku-community/apt` alias (latter waiting on #46 + subsequent manual publish).
