### ISSUE TITLE
Compiling fails with custom apt repo

### ISSUE THREAD

**Issue by Jachobsen** [heroku/heroku-buildpack-apt#83]
I've been using `heroku/python` + `heroku-buildpack-apt` for 3+ years with the following `Aptfile` to build [maxminds C extension](https://github.com/maxmind/libmaxminddb/blob/main/README.md):

```
:repo:deb http://ppa.launchpad.net/maxmind/ppa/ubuntu xenial main
libmaxminddb0 libmaxminddb-dev mmdb-bin
```

but for some reason deploys started failing since about a week ago.

Build log shows very limited information:
```
remote: Compressing source files... done.
remote: Building source:
remote:
remote: -----> Building on the Heroku-20 stack
remote: -----> Apt app detected
remote: -----> Detected Aptfile or Stack changes, flushing cache
remote: -----> Adding custom repositories
remote: -----> Updating apt caches
remote:        Get:1 http://ppa.launchpad.net/maxmind/ppa/ubuntu focal InRelease [18.1 kB]
remote:        Hit:2 http://archive.ubuntu.com/ubuntu focal InRelease
remote:        Get:3 http://archive.ubuntu.com/ubuntu focal-security InRelease [109 kB]
remote:        Err:1 http://ppa.launchpad.net/maxmind/ppa/ubuntu focal InRelease
remote:          The following signatures couldn't be verified because the public key is not available: NO_PUBKEY DE1997DCDE742AFA
remote:        Hit:4 http://apt.postgresql.org/pub/repos/apt focal-pgdg InRelease
remote:        Get:5 http://archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]
remote:        Get:6 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages [974 kB]
remote:        Get:7 http://archive.ubuntu.com/ubuntu focal-updates/universe amd64 Packages [910 kB]
remote:        Reading package lists...
remote: W: GPG error: http://ppa.launchpad.net/maxmind/ppa/ubuntu focal InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY DE1997DCDE742AFA
remote: E: The repository 'http://ppa.launchpad.net/maxmind/ppa/ubuntu focal InRelease' is not signed.
remote:  !     Push rejected, failed to compile Apt app.
remote:
remote:  !     Push failed
```

It started out on the Heroku-18 stack but upgrading to Heroku-20 didn't change anything. I also tried changing the repository list to `focal main` which made no difference.

The GPG warning + "repository is not signed" error hasn't previously stopped builds from compiling.

Pushing a branch with an empty `Aptfile` results in a successful deploy.

Any idea why this suddenly breaks after 3+ years?

**Comment by edmorley** [comment]
Hi!

Try removing the `:repo:deb http://ppa.launchpad.net/maxmind/ppa/ubuntu xenial main` and the build should now succeed.

Previously the APT buildpack ignored errors and continued the build regardless. Now after #79, any failures result in the build aborting correctly. For more details see:
https://github.com/heroku/heroku-buildpack-apt/pull/79#issuecomment-762333105

At a guess I would imagine the reason your builds appeared to work as expected before, was that the packages were previously being installed from the standard Ubuntu APT repository (eg https://packages.ubuntu.com/focal-updates/libmaxminddb0) - ie: the `:repo:deb http://ppa.launchpad.net/maxmind/ppa/ubuntu xenial main` line wasn't doing anything.

**Comment by Jachobsen** [comment]
That did it! Thank you very much for the explanation, that sounds reasonable. 

And thanks for being so responsive. I thought I had traversed the repo for possible causes, but managed to overlook your solution already mentioned in #79.

**Comment by edmorley** [comment]
No problem! Glad that resolved it :-)
