### ISSUE TITLE
Something's broken with custom repos

### ISSUE THREAD

**Issue by lfr** [heroku/heroku-buildpack-apt#84]
The following Aptfile used to work a few weeks ago:
```
:repo:deb [trusted=yes arch=amd64] https://packages.microsoft.com/ubuntu/16.04/prod xenial main
dotnet-sdk-5.0
```
Now it generates the following error during build:
```
-----> Fetching ﻿:repo:deb
       curl: (3) URL using bad/illegal format or missing URL
 !     Push rejected, failed to compile Apt app.
```
This happens both with edge and standard versions

**Comment by edmorley** [comment]
Hi! See: https://github.com/heroku/heroku-buildpack-apt/pull/79#issuecomment-762333105

**Comment by lfr** [comment]
> Hi! See: [#79 (comment)](https://github.com/heroku/heroku-buildpack-apt/pull/79#issuecomment-762333105)

That seems to refer to pre-existing errors that weren't properly reported before. This cannot possibly be the issue I'm having as I only have one entry in the Apt file, and it was properly installed before because I saw in the logs the installation process, also nothing in my app would work without that package (it's a dotnet app so dotnet was obviously properly installed).

**Comment by lfr** [comment]
I've updated my comment, clearly #79 is not applicable here, and removing the :repo:deb is obviously not the solution.

**Comment by lfr** [comment]
Turns out it was an invisible control character in the Aptfile that was causing my error

**Comment by edmorley** [comment]
@lfr Ah that makes sense - thank you for posting back with the reason. Sorry it was such a pain to debug!
